version: 1
settings:
  ws_address: "ws://<YOUR_WS_ADDRESS>:<YOUR_WS_PORT>" # WebSocket服务的地址
  app_id: <YOUR_APP_ID>                              # 你的应用ID
  token: "<YOUR_APP_TOKEN>"                          # 你的应用令牌
  client_secret: "<YOUR_CLIENT_SECRET>"              # 你的客户端密钥
text_intent:                                        #请根据公域 私域来选择intent,错误的intent将连接失败
    - "ATMessageEventHandler"                       # 频道at信息
    - "DirectMessageHandler"                        # 私域频道私信(dms)
    # - "ReadyHandler"                              # 连接成功
    # - "ErrorNotifyHandler"                        # 连接关闭
    # - "GuildEventHandler"                         # 频道事件
    # - "MemberEventHandler"                        # 频道成员新增
    # - "ChannelEventHandler"                       # 频道事件
    # - "CreateMessageHandler"                      # 频道不at信息
    # - "InteractionHandler"                        # 添加频道互动回应
    # - "GroupATMessageEventHandler"                # 群at信息 仅频道机器人时候需要注释
    # - "C2CMessageEventHandler"                    # 群私聊  仅频道机器人时候需要注释
    # - "ThreadEventHandler"                        # 发帖事件 (当前版本已禁用)
  global_channel_to_group: false                     # 是否将频道转换成群
  global_private_to_channel: false                   # 是否将私聊转换成频道
  array: false