/* tslint:disable */
/* eslint-disable */
/**
 * nonebot-plugin-gocqhttp
 * go-cqhttp process manager API
 *
 * The version of the OpenAPI document: 0.6.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

