// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: fileinfo.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义主体消息
type Main struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *Main_A `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Main) Reset() {
	*x = Main{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main) ProtoMessage() {}

func (x *Main) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main.ProtoReflect.Descriptor instead.
func (*Main) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0}
}

func (x *Main) GetA() *Main_A {
	if x != nil {
		return x.A
	}
	return nil
}

// 其他字段
type Other struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtherField uint32 `protobuf:"varint,2,opt,name=other_field,json=otherField,proto3" json:"other_field,omitempty"` // 仅示例，实际中可能不需要
}

func (x *Other) Reset() {
	*x = Other{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Other) ProtoMessage() {}

func (x *Other) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Other.ProtoReflect.Descriptor instead.
func (*Other) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{1}
}

func (x *Other) GetOtherField() uint32 {
	if x != nil {
		return x.OtherField
	}
	return 0
}

type Main_A struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B         *Main_A_B `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	ImageData *Main_A_E `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *Main_A) Reset() {
	*x = Main_A{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A) ProtoMessage() {}

func (x *Main_A) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A.ProtoReflect.Descriptor instead.
func (*Main_A) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Main_A) GetB() *Main_A_B {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Main_A) GetImageData() *Main_A_E {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type Main_A_B struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *Main_A_B_C `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *Main_A_B) Reset() {
	*x = Main_A_B{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_B) ProtoMessage() {}

func (x *Main_A_B) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_B.ProtoReflect.Descriptor instead.
func (*Main_A_B) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Main_A_B) GetInfo() *Main_A_B_C {
	if x != nil {
		return x.Info
	}
	return nil
}

type Main_A_E struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width     uint32      `protobuf:"varint,22,opt,name=width,proto3" json:"width,omitempty"`   // 图片宽度
	Height    uint32      `protobuf:"varint,23,opt,name=height,proto3" json:"height,omitempty"` // 图片高度
	ImageInfo *Main_A_E_F `protobuf:"bytes,34,opt,name=image_info,json=imageInfo,proto3" json:"image_info,omitempty"`
}

func (x *Main_A_E) Reset() {
	*x = Main_A_E{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_E) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_E) ProtoMessage() {}

func (x *Main_A_E) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_E.ProtoReflect.Descriptor instead.
func (*Main_A_E) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Main_A_E) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Main_A_E) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Main_A_E) GetImageInfo() *Main_A_E_F {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

type Main_A_B_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail *Main_A_B_C_D `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *Main_A_B_C) Reset() {
	*x = Main_A_B_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_B_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_B_C) ProtoMessage() {}

func (x *Main_A_B_C) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_B_C.ProtoReflect.Descriptor instead.
func (*Main_A_B_C) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Main_A_B_C) GetDetail() *Main_A_B_C_D {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Main_A_B_C_D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupInfo *Main_A_B_C_D_E `protobuf:"bytes,202,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
}

func (x *Main_A_B_C_D) Reset() {
	*x = Main_A_B_C_D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_B_C_D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_B_C_D) ProtoMessage() {}

func (x *Main_A_B_C_D) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_B_C_D.ProtoReflect.Descriptor instead.
func (*Main_A_B_C_D) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *Main_A_B_C_D) GetGroupInfo() *Main_A_B_C_D_E {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type Main_A_B_C_D_E struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupNumber uint64 `protobuf:"varint,1,opt,name=group_number,json=groupNumber,proto3" json:"group_number,omitempty"` // 群号
}

func (x *Main_A_B_C_D_E) Reset() {
	*x = Main_A_B_C_D_E{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_B_C_D_E) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_B_C_D_E) ProtoMessage() {}

func (x *Main_A_B_C_D_E) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_B_C_D_E.ProtoReflect.Descriptor instead.
func (*Main_A_B_C_D_E) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0}
}

func (x *Main_A_B_C_D_E) GetGroupNumber() uint64 {
	if x != nil {
		return x.GroupNumber
	}
	return 0
}

type Main_A_E_F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,30,opt,name=url,proto3" json:"url,omitempty"` // 图片URL
}

func (x *Main_A_E_F) Reset() {
	*x = Main_A_E_F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_A_E_F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_A_E_F) ProtoMessage() {}

func (x *Main_A_E_F) ProtoReflect() protoreflect.Message {
	mi := &file_fileinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_A_E_F.ProtoReflect.Descriptor instead.
func (*Main_A_E_F) Descriptor() ([]byte, []int) {
	return file_fileinfo_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *Main_A_E_F) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_fileinfo_proto protoreflect.FileDescriptor

var file_fileinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xcd, 0x03, 0x0a, 0x04, 0x4d,
	0x61, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x2e, 0x41,
	0x52, 0x01, 0x61, 0x1a, 0xa4, 0x03, 0x0a, 0x01, 0x41, 0x12, 0x20, 0x0a, 0x01, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x2e, 0x42, 0x52, 0x01, 0x62, 0x12, 0x31, 0x0a, 0x0a, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x2e,
	0x41, 0x2e, 0x45, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0xca,
	0x01, 0x0a, 0x01, 0x42, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x61,
	0x69, 0x6e, 0x2e, 0x41, 0x2e, 0x42, 0x2e, 0x43, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x9a,
	0x01, 0x0a, 0x01, 0x43, 0x12, 0x2e, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x2e, 0x42, 0x2e, 0x43, 0x2e, 0x44, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x1a, 0x65, 0x0a, 0x01, 0x44, 0x12, 0x38, 0x0a, 0x0a, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0xca, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x2e, 0x41,
	0x2e, 0x42, 0x2e, 0x43, 0x2e, 0x44, 0x2e, 0x45, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x26, 0x0a, 0x01, 0x45, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x7d, 0x0a, 0x01, 0x45,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x33,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x22, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x61,
	0x69, 0x6e, 0x2e, 0x41, 0x2e, 0x45, 0x2e, 0x46, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x0a, 0x01, 0x46, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x28, 0x0a, 0x05, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x73, 0x68, 0x69, 0x6e, 0x6f, 0x6e, 0x79, 0x61, 0x72, 0x75, 0x6b,
	0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x73, 0x6f, 0x6b, 0x79, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileinfo_proto_rawDescOnce sync.Once
	file_fileinfo_proto_rawDescData = file_fileinfo_proto_rawDesc
)

func file_fileinfo_proto_rawDescGZIP() []byte {
	file_fileinfo_proto_rawDescOnce.Do(func() {
		file_fileinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileinfo_proto_rawDescData)
	})
	return file_fileinfo_proto_rawDescData
}

var file_fileinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fileinfo_proto_goTypes = []interface{}{
	(*Main)(nil),           // 0: protobuf.Main
	(*Other)(nil),          // 1: protobuf.Other
	(*Main_A)(nil),         // 2: protobuf.Main.A
	(*Main_A_B)(nil),       // 3: protobuf.Main.A.B
	(*Main_A_E)(nil),       // 4: protobuf.Main.A.E
	(*Main_A_B_C)(nil),     // 5: protobuf.Main.A.B.C
	(*Main_A_B_C_D)(nil),   // 6: protobuf.Main.A.B.C.D
	(*Main_A_B_C_D_E)(nil), // 7: protobuf.Main.A.B.C.D.E
	(*Main_A_E_F)(nil),     // 8: protobuf.Main.A.E.F
}
var file_fileinfo_proto_depIdxs = []int32{
	2, // 0: protobuf.Main.a:type_name -> protobuf.Main.A
	3, // 1: protobuf.Main.A.b:type_name -> protobuf.Main.A.B
	4, // 2: protobuf.Main.A.image_data:type_name -> protobuf.Main.A.E
	5, // 3: protobuf.Main.A.B.info:type_name -> protobuf.Main.A.B.C
	8, // 4: protobuf.Main.A.E.image_info:type_name -> protobuf.Main.A.E.F
	6, // 5: protobuf.Main.A.B.C.detail:type_name -> protobuf.Main.A.B.C.D
	7, // 6: protobuf.Main.A.B.C.D.group_info:type_name -> protobuf.Main.A.B.C.D.E
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_fileinfo_proto_init() }
func file_fileinfo_proto_init() {
	if File_fileinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Other); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_B); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_E); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_B_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_B_C_D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_B_C_D_E); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_A_E_F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fileinfo_proto_goTypes,
		DependencyIndexes: file_fileinfo_proto_depIdxs,
		MessageInfos:      file_fileinfo_proto_msgTypes,
	}.Build()
	File_fileinfo_proto = out.File
	file_fileinfo_proto_rawDesc = nil
	file_fileinfo_proto_goTypes = nil
	file_fileinfo_proto_depIdxs = nil
}
