// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: idmap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求消息和响应消息
type StoreIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
}

func (x *StoreIDRequest) Reset() {
	*x = StoreIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDRequest) ProtoMessage() {}

func (x *StoreIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDRequest.ProtoReflect.Descriptor instead.
func (*StoreIDRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{0}
}

func (x *StoreIDRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

type StoreIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row int64 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
}

func (x *StoreIDResponse) Reset() {
	*x = StoreIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDResponse) ProtoMessage() {}

func (x *StoreIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDResponse.ProtoReflect.Descriptor instead.
func (*StoreIDResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{1}
}

func (x *StoreIDResponse) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

type RetrieveRowByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
}

func (x *RetrieveRowByIDRequest) Reset() {
	*x = RetrieveRowByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByIDRequest) ProtoMessage() {}

func (x *RetrieveRowByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByIDRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRowByIDRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRowByIDRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

type RetrieveRowByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RetrieveRowByIDResponse) Reset() {
	*x = RetrieveRowByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByIDResponse) ProtoMessage() {}

func (x *RetrieveRowByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByIDResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRowByIDResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveRowByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WriteConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section string `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Subtype string `protobuf:"bytes,2,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WriteConfigRequest) Reset() {
	*x = WriteConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigRequest) ProtoMessage() {}

func (x *WriteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigRequest.ProtoReflect.Descriptor instead.
func (*WriteConfigRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{4}
}

func (x *WriteConfigRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *WriteConfigRequest) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *WriteConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WriteConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WriteConfigResponse) Reset() {
	*x = WriteConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigResponse) ProtoMessage() {}

func (x *WriteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigResponse.ProtoReflect.Descriptor instead.
func (*WriteConfigResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{5}
}

func (x *WriteConfigResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReadConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section string `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Subtype string `protobuf:"bytes,2,opt,name=subtype,proto3" json:"subtype,omitempty"`
}

func (x *ReadConfigRequest) Reset() {
	*x = ReadConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigRequest) ProtoMessage() {}

func (x *ReadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReadConfigRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{6}
}

func (x *ReadConfigRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ReadConfigRequest) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

type ReadConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReadConfigResponse) Reset() {
	*x = ReadConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigResponse) ProtoMessage() {}

func (x *ReadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReadConfigResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{7}
}

func (x *ReadConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateVirtualValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldVirtualValue int64 `protobuf:"varint,1,opt,name=old_virtual_value,json=oldVirtualValue,proto3" json:"old_virtual_value,omitempty"`
	NewVirtualValue int64 `protobuf:"varint,2,opt,name=new_virtual_value,json=newVirtualValue,proto3" json:"new_virtual_value,omitempty"`
}

func (x *UpdateVirtualValueRequest) Reset() {
	*x = UpdateVirtualValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVirtualValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualValueRequest) ProtoMessage() {}

func (x *UpdateVirtualValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateVirtualValueRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateVirtualValueRequest) GetOldVirtualValue() int64 {
	if x != nil {
		return x.OldVirtualValue
	}
	return 0
}

func (x *UpdateVirtualValueRequest) GetNewVirtualValue() int64 {
	if x != nil {
		return x.NewVirtualValue
	}
	return 0
}

type UpdateVirtualValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateVirtualValueResponse) Reset() {
	*x = UpdateVirtualValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVirtualValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualValueResponse) ProtoMessage() {}

func (x *UpdateVirtualValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualValueResponse.ProtoReflect.Descriptor instead.
func (*UpdateVirtualValueResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVirtualValueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RetrieveRealValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualValue int64 `protobuf:"varint,1,opt,name=virtual_value,json=virtualValue,proto3" json:"virtual_value,omitempty"`
}

func (x *RetrieveRealValueRequest) Reset() {
	*x = RetrieveRealValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRealValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRealValueRequest) ProtoMessage() {}

func (x *RetrieveRealValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRealValueRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRealValueRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveRealValueRequest) GetVirtualValue() int64 {
	if x != nil {
		return x.VirtualValue
	}
	return 0
}

type RetrieveRealValueRequestPro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualValue    int64 `protobuf:"varint,1,opt,name=virtual_value,json=virtualValue,proto3" json:"virtual_value,omitempty"`
	VirtualValueSub int64 `protobuf:"varint,2,opt,name=virtual_value_sub,json=virtualValueSub,proto3" json:"virtual_value_sub,omitempty"`
}

func (x *RetrieveRealValueRequestPro) Reset() {
	*x = RetrieveRealValueRequestPro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRealValueRequestPro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRealValueRequestPro) ProtoMessage() {}

func (x *RetrieveRealValueRequestPro) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRealValueRequestPro.ProtoReflect.Descriptor instead.
func (*RetrieveRealValueRequestPro) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveRealValueRequestPro) GetVirtualValue() int64 {
	if x != nil {
		return x.VirtualValue
	}
	return 0
}

func (x *RetrieveRealValueRequestPro) GetVirtualValueSub() int64 {
	if x != nil {
		return x.VirtualValueSub
	}
	return 0
}

type RetrieveRealValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Virtual string `protobuf:"bytes,1,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Real    string `protobuf:"bytes,2,opt,name=real,proto3" json:"real,omitempty"`
}

func (x *RetrieveRealValueResponse) Reset() {
	*x = RetrieveRealValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRealValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRealValueResponse) ProtoMessage() {}

func (x *RetrieveRealValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRealValueResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRealValueResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{12}
}

func (x *RetrieveRealValueResponse) GetVirtual() string {
	if x != nil {
		return x.Virtual
	}
	return ""
}

func (x *RetrieveRealValueResponse) GetReal() string {
	if x != nil {
		return x.Real
	}
	return ""
}

type RetrieveRealValueResponsePro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Virtual string `protobuf:"bytes,1,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Real    string `protobuf:"bytes,2,opt,name=real,proto3" json:"real,omitempty"`
}

func (x *RetrieveRealValueResponsePro) Reset() {
	*x = RetrieveRealValueResponsePro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRealValueResponsePro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRealValueResponsePro) ProtoMessage() {}

func (x *RetrieveRealValueResponsePro) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRealValueResponsePro.ProtoReflect.Descriptor instead.
func (*RetrieveRealValueResponsePro) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{13}
}

func (x *RetrieveRealValueResponsePro) GetVirtual() string {
	if x != nil {
		return x.Virtual
	}
	return ""
}

func (x *RetrieveRealValueResponsePro) GetReal() string {
	if x != nil {
		return x.Real
	}
	return ""
}

type RetrieveVirtualValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealValue string `protobuf:"bytes,1,opt,name=real_value,json=realValue,proto3" json:"real_value,omitempty"`
}

func (x *RetrieveVirtualValueRequest) Reset() {
	*x = RetrieveVirtualValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveVirtualValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveVirtualValueRequest) ProtoMessage() {}

func (x *RetrieveVirtualValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveVirtualValueRequest.ProtoReflect.Descriptor instead.
func (*RetrieveVirtualValueRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{14}
}

func (x *RetrieveVirtualValueRequest) GetRealValue() string {
	if x != nil {
		return x.RealValue
	}
	return ""
}

type RetrieveVirtualValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Real    string `protobuf:"bytes,1,opt,name=real,proto3" json:"real,omitempty"`
	Virtual string `protobuf:"bytes,2,opt,name=virtual,proto3" json:"virtual,omitempty"`
}

func (x *RetrieveVirtualValueResponse) Reset() {
	*x = RetrieveVirtualValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveVirtualValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveVirtualValueResponse) ProtoMessage() {}

func (x *RetrieveVirtualValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveVirtualValueResponse.ProtoReflect.Descriptor instead.
func (*RetrieveVirtualValueResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{15}
}

func (x *RetrieveVirtualValueResponse) GetReal() string {
	if x != nil {
		return x.Real
	}
	return ""
}

func (x *RetrieveVirtualValueResponse) GetVirtual() string {
	if x != nil {
		return x.Virtual
	}
	return ""
}

type StoreIDProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
	Subid   string `protobuf:"bytes,2,opt,name=subid,proto3" json:"subid,omitempty"`
}

func (x *StoreIDProRequest) Reset() {
	*x = StoreIDProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIDProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDProRequest) ProtoMessage() {}

func (x *StoreIDProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDProRequest.ProtoReflect.Descriptor instead.
func (*StoreIDProRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{16}
}

func (x *StoreIDProRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

func (x *StoreIDProRequest) GetSubid() string {
	if x != nil {
		return x.Subid
	}
	return ""
}

type StoreIDProResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    int64 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	SubRow int64 `protobuf:"varint,2,opt,name=sub_row,json=subRow,proto3" json:"sub_row,omitempty"`
}

func (x *StoreIDProResponse) Reset() {
	*x = StoreIDProResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreIDProResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIDProResponse) ProtoMessage() {}

func (x *StoreIDProResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIDProResponse.ProtoReflect.Descriptor instead.
func (*StoreIDProResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{17}
}

func (x *StoreIDProResponse) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *StoreIDProResponse) GetSubRow() int64 {
	if x != nil {
		return x.SubRow
	}
	return 0
}

type RetrieveRowByIDProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
	Subid   string `protobuf:"bytes,2,opt,name=subid,proto3" json:"subid,omitempty"`
}

func (x *RetrieveRowByIDProRequest) Reset() {
	*x = RetrieveRowByIDProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByIDProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByIDProRequest) ProtoMessage() {}

func (x *RetrieveRowByIDProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByIDProRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRowByIDProRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{18}
}

func (x *RetrieveRowByIDProRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

func (x *RetrieveRowByIDProRequest) GetSubid() string {
	if x != nil {
		return x.Subid
	}
	return ""
}

type RetrieveRowByIDProResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subid string `protobuf:"bytes,2,opt,name=subid,proto3" json:"subid,omitempty"`
}

func (x *RetrieveRowByIDProResponse) Reset() {
	*x = RetrieveRowByIDProResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByIDProResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByIDProResponse) ProtoMessage() {}

func (x *RetrieveRowByIDProResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByIDProResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRowByIDProResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{19}
}

func (x *RetrieveRowByIDProResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetrieveRowByIDProResponse) GetSubid() string {
	if x != nil {
		return x.Subid
	}
	return ""
}

type RetrieveVirtualValueProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
	Subid   string `protobuf:"bytes,2,opt,name=subid,proto3" json:"subid,omitempty"`
}

func (x *RetrieveVirtualValueProRequest) Reset() {
	*x = RetrieveVirtualValueProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveVirtualValueProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveVirtualValueProRequest) ProtoMessage() {}

func (x *RetrieveVirtualValueProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveVirtualValueProRequest.ProtoReflect.Descriptor instead.
func (*RetrieveVirtualValueProRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{20}
}

func (x *RetrieveVirtualValueProRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

func (x *RetrieveVirtualValueProRequest) GetSubid() string {
	if x != nil {
		return x.Subid
	}
	return ""
}

type RetrieveVirtualValueProResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstValue  string `protobuf:"bytes,1,opt,name=first_value,json=firstValue,proto3" json:"first_value,omitempty"`
	SecondValue string `protobuf:"bytes,2,opt,name=second_value,json=secondValue,proto3" json:"second_value,omitempty"`
}

func (x *RetrieveVirtualValueProResponse) Reset() {
	*x = RetrieveVirtualValueProResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveVirtualValueProResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveVirtualValueProResponse) ProtoMessage() {}

func (x *RetrieveVirtualValueProResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveVirtualValueProResponse.ProtoReflect.Descriptor instead.
func (*RetrieveVirtualValueProResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{21}
}

func (x *RetrieveVirtualValueProResponse) GetFirstValue() string {
	if x != nil {
		return x.FirstValue
	}
	return ""
}

func (x *RetrieveVirtualValueProResponse) GetSecondValue() string {
	if x != nil {
		return x.SecondValue
	}
	return ""
}

type UpdateVirtualValueProRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldVirtualValue_1 int64 `protobuf:"varint,1,opt,name=old_virtual_value_1,json=oldVirtualValue1,proto3" json:"old_virtual_value_1,omitempty"`
	NewVirtualValue_1 int64 `protobuf:"varint,2,opt,name=new_virtual_value_1,json=newVirtualValue1,proto3" json:"new_virtual_value_1,omitempty"`
	OldVirtualValue_2 int64 `protobuf:"varint,3,opt,name=old_virtual_value_2,json=oldVirtualValue2,proto3" json:"old_virtual_value_2,omitempty"`
	NewVirtualValue_2 int64 `protobuf:"varint,4,opt,name=new_virtual_value_2,json=newVirtualValue2,proto3" json:"new_virtual_value_2,omitempty"`
}

func (x *UpdateVirtualValueProRequest) Reset() {
	*x = UpdateVirtualValueProRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVirtualValueProRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualValueProRequest) ProtoMessage() {}

func (x *UpdateVirtualValueProRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualValueProRequest.ProtoReflect.Descriptor instead.
func (*UpdateVirtualValueProRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateVirtualValueProRequest) GetOldVirtualValue_1() int64 {
	if x != nil {
		return x.OldVirtualValue_1
	}
	return 0
}

func (x *UpdateVirtualValueProRequest) GetNewVirtualValue_1() int64 {
	if x != nil {
		return x.NewVirtualValue_1
	}
	return 0
}

func (x *UpdateVirtualValueProRequest) GetOldVirtualValue_2() int64 {
	if x != nil {
		return x.OldVirtualValue_2
	}
	return 0
}

func (x *UpdateVirtualValueProRequest) GetNewVirtualValue_2() int64 {
	if x != nil {
		return x.NewVirtualValue_2
	}
	return 0
}

type UpdateVirtualValueProResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateVirtualValueProResponse) Reset() {
	*x = UpdateVirtualValueProResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVirtualValueProResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualValueProResponse) ProtoMessage() {}

func (x *UpdateVirtualValueProResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualValueProResponse.ProtoReflect.Descriptor instead.
func (*UpdateVirtualValueProResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateVirtualValueProResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SimplifiedStoreIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
}

func (x *SimplifiedStoreIDRequest) Reset() {
	*x = SimplifiedStoreIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplifiedStoreIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplifiedStoreIDRequest) ProtoMessage() {}

func (x *SimplifiedStoreIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplifiedStoreIDRequest.ProtoReflect.Descriptor instead.
func (*SimplifiedStoreIDRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{24}
}

func (x *SimplifiedStoreIDRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

type SimplifiedStoreIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row int64 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
}

func (x *SimplifiedStoreIDResponse) Reset() {
	*x = SimplifiedStoreIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplifiedStoreIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplifiedStoreIDResponse) ProtoMessage() {}

func (x *SimplifiedStoreIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplifiedStoreIDResponse.ProtoReflect.Descriptor instead.
func (*SimplifiedStoreIDResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{25}
}

func (x *SimplifiedStoreIDResponse) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

type FindSubKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindSubKeysRequest) Reset() {
	*x = FindSubKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSubKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSubKeysRequest) ProtoMessage() {}

func (x *FindSubKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSubKeysRequest.ProtoReflect.Descriptor instead.
func (*FindSubKeysRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{26}
}

func (x *FindSubKeysRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindSubKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *FindSubKeysResponse) Reset() {
	*x = FindSubKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSubKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSubKeysResponse) ProtoMessage() {}

func (x *FindSubKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSubKeysResponse.ProtoReflect.Descriptor instead.
func (*FindSubKeysResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{27}
}

func (x *FindSubKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section string `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Subtype string `protobuf:"bytes,2,opt,name=subtype,proto3" json:"subtype,omitempty"`
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteConfigRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *DeleteConfigRequest) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteConfigResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StoreCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
}

func (x *StoreCacheRequest) Reset() {
	*x = StoreCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCacheRequest) ProtoMessage() {}

func (x *StoreCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCacheRequest.ProtoReflect.Descriptor instead.
func (*StoreCacheRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{30}
}

func (x *StoreCacheRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

type StoreCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row int64 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
}

func (x *StoreCacheResponse) Reset() {
	*x = StoreCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCacheResponse) ProtoMessage() {}

func (x *StoreCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCacheResponse.ProtoReflect.Descriptor instead.
func (*StoreCacheResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{31}
}

func (x *StoreCacheResponse) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

type RetrieveRowByCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdOrRow string `protobuf:"bytes,1,opt,name=id_or_row,json=idOrRow,proto3" json:"id_or_row,omitempty"`
}

func (x *RetrieveRowByCacheRequest) Reset() {
	*x = RetrieveRowByCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByCacheRequest) ProtoMessage() {}

func (x *RetrieveRowByCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByCacheRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRowByCacheRequest) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{32}
}

func (x *RetrieveRowByCacheRequest) GetIdOrRow() string {
	if x != nil {
		return x.IdOrRow
	}
	return ""
}

type RetrieveRowByCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RetrieveRowByCacheResponse) Reset() {
	*x = RetrieveRowByCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idmap_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveRowByCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRowByCacheResponse) ProtoMessage() {}

func (x *RetrieveRowByCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idmap_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRowByCacheResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRowByCacheResponse) Descriptor() ([]byte, []int) {
	return file_idmap_proto_rawDescGZIP(), []int{33}
}

func (x *RetrieveRowByCacheResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_idmap_proto protoreflect.FileDescriptor

var file_idmap_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x64, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x22, 0x23, 0x0a, 0x0f, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x6f, 0x77,
	0x22, 0x34, 0x0a, 0x16, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x09, 0x69, 0x64,
	0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x22, 0x29, 0x0a, 0x17, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x5e, 0x0a, 0x12, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x2d, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x47, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x73, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x6c, 0x64, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6f,
	0x6c, 0x64, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a,
	0x0a, 0x11, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a, 0x1a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x3f, 0x0a, 0x18, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x6e, 0x0a, 0x1b, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x12, 0x23, 0x0a, 0x0d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x75,
	0x62, 0x22, 0x49, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x1c,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x22, 0x3c, 0x0a, 0x1b, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x61,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x1c, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x44, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x09, 0x69,
	0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x69, 0x64, 0x22, 0x3f, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x5f, 0x72, 0x6f, 0x77,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x75, 0x62, 0x52, 0x6f, 0x77, 0x22, 0x4d,
	0x0a, 0x19, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49,
	0x44, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x09, 0x69,
	0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x69, 0x64, 0x22, 0x42, 0x0a,
	0x1a, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44,
	0x50, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x75, 0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x69,
	0x64, 0x22, 0x52, 0x0a, 0x1e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x75, 0x62, 0x69, 0x64, 0x22, 0x65, 0x0a, 0x1f, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xda, 0x01, 0x0a,
	0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x13, 0x6f, 0x6c, 0x64, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6f, 0x6c, 0x64, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x2d, 0x0a, 0x13,
	0x6e, 0x65, 0x77, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x65, 0x77, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x2d, 0x0a, 0x13, 0x6f,
	0x6c, 0x64, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6f, 0x6c, 0x64, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x12, 0x2d, 0x0a, 0x13, 0x6e, 0x65,
	0x77, 0x5f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f,
	0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x65, 0x77, 0x56, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x39, 0x0a, 0x1d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50,
	0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x18, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x22, 0x2d, 0x0a, 0x19,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x24, 0x0a, 0x12, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x29, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x49, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x09,
	0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x22, 0x26, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x6f, 0x77,
	0x22, 0x37, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42,
	0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x09, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x64, 0x4f, 0x72, 0x52, 0x6f, 0x77, 0x22, 0x2c, 0x0a, 0x1a, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xe4, 0x09, 0x0a, 0x0c, 0x49, 0x44, 0x4d, 0x61,
	0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x56, 0x32, 0x12, 0x0f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44, 0x56, 0x32, 0x12, 0x17, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56,
	0x32, 0x12, 0x13, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x32, 0x12, 0x12, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x32, 0x12, 0x1a, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x32, 0x12, 0x19, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x16, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x32, 0x50, 0x72, 0x6f, 0x12, 0x1c,
	0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x1a, 0x1d, 0x2e, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x12, 0x55, 0x0a, 0x16, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x56, 0x32, 0x12, 0x1c, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x56, 0x32, 0x50,
	0x72, 0x6f, 0x12, 0x12, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44,
	0x50, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49, 0x44, 0x56, 0x32,
	0x50, 0x72, 0x6f, 0x12, 0x1a, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f,
	0x77, 0x42, 0x79, 0x49, 0x44, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x49,
	0x44, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x19,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x56, 0x32, 0x50, 0x72, 0x6f, 0x12, 0x1f, 0x2e, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x50, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x52, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x17,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x56, 0x32, 0x50, 0x72, 0x6f, 0x12, 0x1d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x56, 0x32, 0x12, 0x19, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x73, 0x42, 0x79, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x12, 0x13, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x53, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x32, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x56, 0x32, 0x12, 0x12, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x14, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x56, 0x32, 0x12, 0x1a, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x52, 0x6f, 0x77, 0x42, 0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x42,
	0x79, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x73,
	0x68, 0x69, 0x6e, 0x6f, 0x6e, 0x79, 0x61, 0x72, 0x75, 0x6b, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x73,
	0x6f, 0x6b, 0x79, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_idmap_proto_rawDescOnce sync.Once
	file_idmap_proto_rawDescData = file_idmap_proto_rawDesc
)

func file_idmap_proto_rawDescGZIP() []byte {
	file_idmap_proto_rawDescOnce.Do(func() {
		file_idmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_idmap_proto_rawDescData)
	})
	return file_idmap_proto_rawDescData
}

var file_idmap_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_idmap_proto_goTypes = []interface{}{
	(*StoreIDRequest)(nil),                  // 0: StoreIDRequest
	(*StoreIDResponse)(nil),                 // 1: StoreIDResponse
	(*RetrieveRowByIDRequest)(nil),          // 2: RetrieveRowByIDRequest
	(*RetrieveRowByIDResponse)(nil),         // 3: RetrieveRowByIDResponse
	(*WriteConfigRequest)(nil),              // 4: WriteConfigRequest
	(*WriteConfigResponse)(nil),             // 5: WriteConfigResponse
	(*ReadConfigRequest)(nil),               // 6: ReadConfigRequest
	(*ReadConfigResponse)(nil),              // 7: ReadConfigResponse
	(*UpdateVirtualValueRequest)(nil),       // 8: UpdateVirtualValueRequest
	(*UpdateVirtualValueResponse)(nil),      // 9: UpdateVirtualValueResponse
	(*RetrieveRealValueRequest)(nil),        // 10: RetrieveRealValueRequest
	(*RetrieveRealValueRequestPro)(nil),     // 11: RetrieveRealValueRequestPro
	(*RetrieveRealValueResponse)(nil),       // 12: RetrieveRealValueResponse
	(*RetrieveRealValueResponsePro)(nil),    // 13: RetrieveRealValueResponsePro
	(*RetrieveVirtualValueRequest)(nil),     // 14: RetrieveVirtualValueRequest
	(*RetrieveVirtualValueResponse)(nil),    // 15: RetrieveVirtualValueResponse
	(*StoreIDProRequest)(nil),               // 16: StoreIDProRequest
	(*StoreIDProResponse)(nil),              // 17: StoreIDProResponse
	(*RetrieveRowByIDProRequest)(nil),       // 18: RetrieveRowByIDProRequest
	(*RetrieveRowByIDProResponse)(nil),      // 19: RetrieveRowByIDProResponse
	(*RetrieveVirtualValueProRequest)(nil),  // 20: RetrieveVirtualValueProRequest
	(*RetrieveVirtualValueProResponse)(nil), // 21: RetrieveVirtualValueProResponse
	(*UpdateVirtualValueProRequest)(nil),    // 22: UpdateVirtualValueProRequest
	(*UpdateVirtualValueProResponse)(nil),   // 23: UpdateVirtualValueProResponse
	(*SimplifiedStoreIDRequest)(nil),        // 24: SimplifiedStoreIDRequest
	(*SimplifiedStoreIDResponse)(nil),       // 25: SimplifiedStoreIDResponse
	(*FindSubKeysRequest)(nil),              // 26: FindSubKeysRequest
	(*FindSubKeysResponse)(nil),             // 27: FindSubKeysResponse
	(*DeleteConfigRequest)(nil),             // 28: DeleteConfigRequest
	(*DeleteConfigResponse)(nil),            // 29: DeleteConfigResponse
	(*StoreCacheRequest)(nil),               // 30: StoreCacheRequest
	(*StoreCacheResponse)(nil),              // 31: StoreCacheResponse
	(*RetrieveRowByCacheRequest)(nil),       // 32: RetrieveRowByCacheRequest
	(*RetrieveRowByCacheResponse)(nil),      // 33: RetrieveRowByCacheResponse
}
var file_idmap_proto_depIdxs = []int32{
	0,  // 0: IDMapService.StoreIDV2:input_type -> StoreIDRequest
	2,  // 1: IDMapService.RetrieveRowByIDV2:input_type -> RetrieveRowByIDRequest
	4,  // 2: IDMapService.WriteConfigV2:input_type -> WriteConfigRequest
	6,  // 3: IDMapService.ReadConfigV2:input_type -> ReadConfigRequest
	8,  // 4: IDMapService.UpdateVirtualValueV2:input_type -> UpdateVirtualValueRequest
	10, // 5: IDMapService.RetrieveRealValueV2:input_type -> RetrieveRealValueRequest
	11, // 6: IDMapService.RetrieveRealValueV2Pro:input_type -> RetrieveRealValueRequestPro
	14, // 7: IDMapService.RetrieveVirtualValueV2:input_type -> RetrieveVirtualValueRequest
	16, // 8: IDMapService.StoreIDV2Pro:input_type -> StoreIDProRequest
	18, // 9: IDMapService.RetrieveRowByIDV2Pro:input_type -> RetrieveRowByIDProRequest
	20, // 10: IDMapService.RetrieveVirtualValueV2Pro:input_type -> RetrieveVirtualValueProRequest
	22, // 11: IDMapService.UpdateVirtualValueV2Pro:input_type -> UpdateVirtualValueProRequest
	24, // 12: IDMapService.SimplifiedStoreIDV2:input_type -> SimplifiedStoreIDRequest
	26, // 13: IDMapService.FindSubKeysByIdPro:input_type -> FindSubKeysRequest
	28, // 14: IDMapService.DeleteConfigV2:input_type -> DeleteConfigRequest
	30, // 15: IDMapService.StoreCacheV2:input_type -> StoreCacheRequest
	32, // 16: IDMapService.RetrieveRowByCacheV2:input_type -> RetrieveRowByCacheRequest
	1,  // 17: IDMapService.StoreIDV2:output_type -> StoreIDResponse
	3,  // 18: IDMapService.RetrieveRowByIDV2:output_type -> RetrieveRowByIDResponse
	5,  // 19: IDMapService.WriteConfigV2:output_type -> WriteConfigResponse
	7,  // 20: IDMapService.ReadConfigV2:output_type -> ReadConfigResponse
	9,  // 21: IDMapService.UpdateVirtualValueV2:output_type -> UpdateVirtualValueResponse
	12, // 22: IDMapService.RetrieveRealValueV2:output_type -> RetrieveRealValueResponse
	13, // 23: IDMapService.RetrieveRealValueV2Pro:output_type -> RetrieveRealValueResponsePro
	15, // 24: IDMapService.RetrieveVirtualValueV2:output_type -> RetrieveVirtualValueResponse
	17, // 25: IDMapService.StoreIDV2Pro:output_type -> StoreIDProResponse
	19, // 26: IDMapService.RetrieveRowByIDV2Pro:output_type -> RetrieveRowByIDProResponse
	21, // 27: IDMapService.RetrieveVirtualValueV2Pro:output_type -> RetrieveVirtualValueProResponse
	23, // 28: IDMapService.UpdateVirtualValueV2Pro:output_type -> UpdateVirtualValueProResponse
	25, // 29: IDMapService.SimplifiedStoreIDV2:output_type -> SimplifiedStoreIDResponse
	27, // 30: IDMapService.FindSubKeysByIdPro:output_type -> FindSubKeysResponse
	29, // 31: IDMapService.DeleteConfigV2:output_type -> DeleteConfigResponse
	31, // 32: IDMapService.StoreCacheV2:output_type -> StoreCacheResponse
	33, // 33: IDMapService.RetrieveRowByCacheV2:output_type -> RetrieveRowByCacheResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_idmap_proto_init() }
func file_idmap_proto_init() {
	if File_idmap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVirtualValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVirtualValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRealValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRealValueRequestPro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRealValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRealValueResponsePro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveVirtualValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveVirtualValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIDProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreIDProResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByIDProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByIDProResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveVirtualValueProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveVirtualValueProResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVirtualValueProRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVirtualValueProResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplifiedStoreIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplifiedStoreIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSubKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSubKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idmap_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveRowByCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idmap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idmap_proto_goTypes,
		DependencyIndexes: file_idmap_proto_depIdxs,
		MessageInfos:      file_idmap_proto_msgTypes,
	}.Build()
	File_idmap_proto = out.File
	file_idmap_proto_rawDesc = nil
	file_idmap_proto_goTypes = nil
	file_idmap_proto_depIdxs = nil
}
